name: Build Android apk

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.0.4'
      - run: flutter pub get
      - run: flutter build apk
      - uses: actions/upload-artifact@v2
        with:
          name: gobetting.apk
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 2